---
- name: Wait for SSH to be established
  wait_for_connection:
    timeout: 300

- name: Disable autoupdates
  script: disable_autoupdate.sh

- name: Remove Canonical snapd
  apt:
    name: snapd
    state: absent
    purge: yes
  become: yes

- name: Update apt-cache
  apt:
    update_cache: yes

- name: Install core applications
  apt:
    name:
      - build-essential
      - gcc
      - jq
    state: latest
    autoclean: yes

- name: Check if pip exists
  register: pip_installed
  command: pip --version
  ignore_errors: true

- name: Else, install pip
  when: pip_installed is failed
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    mode: "preserve"
  
- name: Continue installing pip
  when: pip_installed is failed
  shell: python3 get-pip.py --user

- name: Install awscli
  pip:
    executable: pip3
    name: awscli==1.18.54

- name: Install Docker SDK
  pip:
    executable: pip3
    name: docker==4.2.0