---
- hosts: all
  become: true
  roles:
    - common
    - dask
  vars:
    - master_private_ip: "{{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address'] }}"
    - ansible_python_interpreter: /usr/bin/python3